services:
  treta:
    build: .
    container_name: treta-core
    ports:
      - "7777:7777"

    volumes:
      - ../../data:/data
      - ../../config:/config

    environment:
      - TRETA_ENV=local
      - TRETA_TIMEZONE=Asia/Bangkok
      - TRETA_SCAN_HOUR=9
      - GUMROAD_ACCESS_TOKEN=${GUMROAD_ACCESS_TOKEN}

    stdin_open: true
    tty: true

